// <auto-generated />
using AdatbazisosRajzProj;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdatbazisosRajzProj.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241114105431_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdatbazisosRajzProj.Pont", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<int>("RajzID")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RajzID");

                    b.ToTable("Points");
                });

            modelBuilder.Entity("AdatbazisosRajzProj.Rajz", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Draws");
                });

            modelBuilder.Entity("AdatbazisosRajzProj.Pont", b =>
                {
                    b.HasOne("AdatbazisosRajzProj.Rajz", "Rajz")
                        .WithMany("Pontok")
                        .HasForeignKey("RajzID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rajz");
                });

            modelBuilder.Entity("AdatbazisosRajzProj.Rajz", b =>
                {
                    b.Navigation("Pontok");
                });
#pragma warning restore 612, 618
        }
    }
}
